### ISSUE TITLE
Some rail lines at the bottom of the live map have a different thickness

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-find-rail-zones#17]
Map on https://wmn-find-rail-zones.netlify.app/:

<img width="823" alt="Screenshot 2021-02-15 at 10 10 12" src="https://user-images.githubusercontent.com/62507489/107934082-851d1880-6f77-11eb-966b-8266d5e902df.png">

Map in Illustrator:

![Screenshot 2021-02-15 at 10 21 33](https://user-images.githubusercontent.com/62507489/107934135-96662500-6f77-11eb-84db-106611721027.png)

Some of the train lines at the bottom of the map where the solid line ends and the line with a gradient begins have a different thickness.

Not sure what is causing this as some of the ends of other lines are showing fine on the live map.

**Comment by houbly** [comment]
@jkmnch I've just found the reason for this, the svg export process must have converted the gradient sections of those lines to images and embedded them which means they aren't vectors, so the measurements are in pixels are out of sync. The weird thing is it hasn't done this on all of the paths - some have been converted correctly (e.g. the gradient lines next to Tamworth and Nuneaton). Can you check in illustrator to see if there's any reason it might have exported like that?

**Comment by jkmnch** [comment]
@houbly Thanks for looking the issue up. I've copied the gradient line from Tamworth and replaced the odd ones at the bottom. It's now showing in my Chrome fine now. From what I could see, the layers were the same so I had no idea why some didn't want to display property.

New SVG: 
[RailZoneMap.zip](https://github.com/wmcadigital/wmn-find-rail-zones/files/6023297/RailZoneMap.zip)
